src/Colour.o: \
  src/Colour.hs
src/Geometry.o: \
  src/RatioMath.hs \
  src/Geometry.hs
src/html-palette.o: \
  src/Tankode/Palette/Year2017.hs \
  src/Tankode/Palette/Utils.hs \
  src/Tankode/Palette/Pure.hs \
  src/Tankode/Palette.hs \
  src/html-palette.hs \
  src/Colour.hs
src/html-palette: \
  src/Tankode/Palette/Year2017.hs \
  src/Tankode/Palette/Utils.hs \
  src/Tankode/Palette/Pure.hs \
  src/Tankode/Palette.hs \
  src/html-palette.hs \
  src/Colour.hs
src/List.o: \
  src/List.hs
src/palette.o: \
  src/Tankode/Palette/Year2017.hs \
  src/Tankode/Palette/Utils.hs \
  src/Tankode/Palette/Pure.hs \
  src/Tankode/Palette.hs \
  src/palette.hs \
  src/Colour.hs
src/palette: \
  src/Tankode/Palette/Year2017.hs \
  src/Tankode/Palette/Utils.hs \
  src/Tankode/Palette/Pure.hs \
  src/Tankode/Palette.hs \
  src/palette.hs \
  src/Colour.hs
src/PipeRun.o: \
  src/PipeRun.hs
src/Random.o: \
  src/Random.hs
src/RatioMath.o: \
  src/RatioMath.hs
src/Tankode/Constants.o: \
  src/Tankode/Constants.hs
src/Tankode/Data.o: \
  src/Tankode/Palette/Year2017.hs \
  src/Tankode/Palette/Utils.hs \
  src/Tankode/Palette/Pure.hs \
  src/Tankode/Palette.hs \
  src/Tankode/Data.hs \
  src/RatioMath.hs \
  src/Geometry.hs \
  src/Colour.hs
src/Tankode/IPC.o: \
  src/Tankode/Show.hs \
  src/Tankode/Physics.hs \
  src/Tankode/Palette/Year2017.hs \
  src/Tankode/Palette/Utils.hs \
  src/Tankode/Palette/Pure.hs \
  src/Tankode/Palette.hs \
  src/Tankode/IPC.hs \
  src/Tankode/Data.hs \
  src/Tankode/Constants.hs \
  src/RatioMath.hs \
  src/Random.hs \
  src/PipeRun.hs \
  src/List.hs \
  src/Geometry.hs \
  src/Colour.hs
src/Tankode/Obstacles.o: \
  src/Tankode/Palette/Year2017.hs \
  src/Tankode/Palette/Utils.hs \
  src/Tankode/Palette/Pure.hs \
  src/Tankode/Palette.hs \
  src/Tankode/Obstacles.hs \
  src/Tankode/Data.hs \
  src/RatioMath.hs \
  src/Geometry.hs \
  src/Colour.hs
src/Tankode.o: \
  src/Tankode/Show.hs \
  src/Tankode/Physics.hs \
  src/Tankode/Palette/Year2017.hs \
  src/Tankode/Palette/Utils.hs \
  src/Tankode/Palette/Pure.hs \
  src/Tankode/Palette.hs \
  src/Tankode.hs \
  src/Tankode/IPC.hs \
  src/Tankode/Data.hs \
  src/Tankode/Constants.hs \
  src/RatioMath.hs \
  src/Random.hs \
  src/PipeRun.hs \
  src/List.hs \
  src/Geometry.hs \
  src/Colour.hs
src/Tankode/Palette.o: \
  src/Tankode/Palette/Year2017.hs \
  src/Tankode/Palette/Utils.hs \
  src/Tankode/Palette/Pure.hs \
  src/Tankode/Palette.hs \
  src/Colour.hs
src/Tankode/Palette/Pure.o: \
  src/Tankode/Palette/Utils.hs \
  src/Tankode/Palette/Pure.hs \
  src/Colour.hs
src/Tankode/Palette/Utils.o: \
  src/Tankode/Palette/Utils.hs \
  src/Colour.hs
src/Tankode/Palette/Year2017.o: \
  src/Tankode/Palette/Year2017.hs \
  src/Tankode/Palette/Utils.hs \
  src/Colour.hs
src/Tankode/Physics.o: \
  src/Tankode/Physics.hs \
  src/Tankode/Palette/Year2017.hs \
  src/Tankode/Palette/Utils.hs \
  src/Tankode/Palette/Pure.hs \
  src/Tankode/Palette.hs \
  src/Tankode/Data.hs \
  src/Tankode/Constants.hs \
  src/RatioMath.hs \
  src/Random.hs \
  src/List.hs \
  src/Geometry.hs \
  src/Colour.hs
src/tankode-runner.o: \
  src/Tankode/Show.hs \
  src/tankode-runner.hs \
  src/Tankode/Physics.hs \
  src/Tankode/Palette/Year2017.hs \
  src/Tankode/Palette/Utils.hs \
  src/Tankode/Palette/Pure.hs \
  src/Tankode/Palette.hs \
  src/Tankode.hs \
  src/Tankode/Obstacles.hs \
  src/Tankode/IPC.hs \
  src/Tankode/Data.hs \
  src/Tankode/Constants.hs \
  src/RatioMath.hs \
  src/Random.hs \
  src/PipeRun.hs \
  src/List.hs \
  src/Geometry.hs \
  src/Colour.hs
src/tankode-runner: \
  src/Tankode/Show.hs \
  src/tankode-runner.hs \
  src/Tankode/Physics.hs \
  src/Tankode/Palette/Year2017.hs \
  src/Tankode/Palette/Utils.hs \
  src/Tankode/Palette/Pure.hs \
  src/Tankode/Palette.hs \
  src/Tankode.hs \
  src/Tankode/Obstacles.hs \
  src/Tankode/IPC.hs \
  src/Tankode/Data.hs \
  src/Tankode/Constants.hs \
  src/RatioMath.hs \
  src/Random.hs \
  src/PipeRun.hs \
  src/List.hs \
  src/Geometry.hs \
  src/Colour.hs
src/Tankode/Show.o: \
  src/Tankode/Show.hs \
  src/Tankode/Physics.hs \
  src/Tankode/Palette/Year2017.hs \
  src/Tankode/Palette/Utils.hs \
  src/Tankode/Palette/Pure.hs \
  src/Tankode/Palette.hs \
  src/Tankode/Data.hs \
  src/Tankode/Constants.hs \
  src/RatioMath.hs \
  src/Random.hs \
  src/List.hs \
  src/Geometry.hs \
  src/Colour.hs
src/Trigonometry.o: \
  src/Trigonometry.hs
tests/test-list.o: \
  tests/Test.hs \
  tests/test-list.hs \
  src/Tankode/Show.hs \
  src/Tankode/Physics.hs \
  src/Tankode/Palette/Year2017.hs \
  src/Tankode/Palette/Utils.hs \
  src/Tankode/Palette/Pure.hs \
  src/Tankode/Palette.hs \
  src/Tankode.hs \
  src/Tankode/IPC.hs \
  src/Tankode/Data.hs \
  src/Tankode/Constants.hs \
  src/RatioMath.hs \
  src/Random.hs \
  src/PipeRun.hs \
  src/List.hs \
  src/Geometry.hs \
  src/Colour.hs
tests/test-list: \
  tests/Test.hs \
  tests/test-list.hs \
  src/Tankode/Show.hs \
  src/Tankode/Physics.hs \
  src/Tankode/Palette/Year2017.hs \
  src/Tankode/Palette/Utils.hs \
  src/Tankode/Palette/Pure.hs \
  src/Tankode/Palette.hs \
  src/Tankode.hs \
  src/Tankode/IPC.hs \
  src/Tankode/Data.hs \
  src/Tankode/Constants.hs \
  src/RatioMath.hs \
  src/Random.hs \
  src/PipeRun.hs \
  src/List.hs \
  src/Geometry.hs \
  src/Colour.hs
tests/Test.o: \
  tests/Test.hs \
  src/Tankode/Show.hs \
  src/Tankode/Physics.hs \
  src/Tankode/Palette/Year2017.hs \
  src/Tankode/Palette/Utils.hs \
  src/Tankode/Palette/Pure.hs \
  src/Tankode/Palette.hs \
  src/Tankode.hs \
  src/Tankode/IPC.hs \
  src/Tankode/Data.hs \
  src/Tankode/Constants.hs \
  src/RatioMath.hs \
  src/Random.hs \
  src/PipeRun.hs \
  src/List.hs \
  src/Geometry.hs \
  src/Colour.hs
tests/test-ratiomath.o: \
  tests/test-ratiomath.hs \
  tests/Test.hs \
  src/Tankode/Show.hs \
  src/Tankode/Physics.hs \
  src/Tankode/Palette/Year2017.hs \
  src/Tankode/Palette/Utils.hs \
  src/Tankode/Palette/Pure.hs \
  src/Tankode/Palette.hs \
  src/Tankode.hs \
  src/Tankode/IPC.hs \
  src/Tankode/Data.hs \
  src/Tankode/Constants.hs \
  src/RatioMath.hs \
  src/Random.hs \
  src/PipeRun.hs \
  src/List.hs \
  src/Geometry.hs \
  src/Colour.hs
tests/test-ratiomath: \
  tests/test-ratiomath.hs \
  tests/Test.hs \
  src/Tankode/Show.hs \
  src/Tankode/Physics.hs \
  src/Tankode/Palette/Year2017.hs \
  src/Tankode/Palette/Utils.hs \
  src/Tankode/Palette/Pure.hs \
  src/Tankode/Palette.hs \
  src/Tankode.hs \
  src/Tankode/IPC.hs \
  src/Tankode/Data.hs \
  src/Tankode/Constants.hs \
  src/RatioMath.hs \
  src/Random.hs \
  src/PipeRun.hs \
  src/List.hs \
  src/Geometry.hs \
  src/Colour.hs
tests/test-readshow.o: \
  tests/test-readshow.hs \
  tests/Test.hs \
  src/Tankode/Show.hs \
  src/Tankode/Physics.hs \
  src/Tankode/Palette/Year2017.hs \
  src/Tankode/Palette/Utils.hs \
  src/Tankode/Palette/Pure.hs \
  src/Tankode/Palette.hs \
  src/Tankode.hs \
  src/Tankode/IPC.hs \
  src/Tankode/Data.hs \
  src/Tankode/Constants.hs \
  src/RatioMath.hs \
  src/Random.hs \
  src/PipeRun.hs \
  src/List.hs \
  src/Geometry.hs \
  src/Colour.hs
tests/test-readshow: \
  tests/test-readshow.hs \
  tests/Test.hs \
  src/Tankode/Show.hs \
  src/Tankode/Physics.hs \
  src/Tankode/Palette/Year2017.hs \
  src/Tankode/Palette/Utils.hs \
  src/Tankode/Palette/Pure.hs \
  src/Tankode/Palette.hs \
  src/Tankode.hs \
  src/Tankode/IPC.hs \
  src/Tankode/Data.hs \
  src/Tankode/Constants.hs \
  src/RatioMath.hs \
  src/Random.hs \
  src/PipeRun.hs \
  src/List.hs \
  src/Geometry.hs \
  src/Colour.hs
tests/test-tankode.o: \
  tests/test-tankode.hs \
  tests/Test.hs \
  src/Tankode/Show.hs \
  src/Tankode/Physics.hs \
  src/Tankode/Palette/Year2017.hs \
  src/Tankode/Palette/Utils.hs \
  src/Tankode/Palette/Pure.hs \
  src/Tankode/Palette.hs \
  src/Tankode.hs \
  src/Tankode/IPC.hs \
  src/Tankode/Data.hs \
  src/Tankode/Constants.hs \
  src/RatioMath.hs \
  src/Random.hs \
  src/PipeRun.hs \
  src/List.hs \
  src/Geometry.hs \
  src/Colour.hs
tests/test-tankode: \
  tests/test-tankode.hs \
  tests/Test.hs \
  src/Tankode/Show.hs \
  src/Tankode/Physics.hs \
  src/Tankode/Palette/Year2017.hs \
  src/Tankode/Palette/Utils.hs \
  src/Tankode/Palette/Pure.hs \
  src/Tankode/Palette.hs \
  src/Tankode.hs \
  src/Tankode/IPC.hs \
  src/Tankode/Data.hs \
  src/Tankode/Constants.hs \
  src/RatioMath.hs \
  src/Random.hs \
  src/PipeRun.hs \
  src/List.hs \
  src/Geometry.hs \
  src/Colour.hs
tests/Test: \
  tests/Test.hs \
  src/Tankode/Show.hs \
  src/Tankode/Physics.hs \
  src/Tankode/Palette/Year2017.hs \
  src/Tankode/Palette/Utils.hs \
  src/Tankode/Palette/Pure.hs \
  src/Tankode/Palette.hs \
  src/Tankode.hs \
  src/Tankode/IPC.hs \
  src/Tankode/Data.hs \
  src/Tankode/Constants.hs \
  src/RatioMath.hs \
  src/Random.hs \
  src/PipeRun.hs \
  src/List.hs \
  src/Geometry.hs \
  src/Colour.hs
